### PR TITLE
fix: ignore directive sourcemap error

### PR DESCRIPTION
**Pull request by sapphi-red**
### Description

The upstream issue was not resolved for a while, so adding a workaround.

close https://github.com/vitejs/vite/issues/15012

### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md#pull-request-guidelines) and follow the [PR Title Convention](https://github.com/vitejs/vite-plugin-react/blob/main/.github/commit-convention.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Review by hi-ogawa — APPROVED** [review]
Looks good to me!

**Comment by csantos1113** [comment]
I'm having a hard time understanding how a change on this plugin actually "fixed" an issue in `vite` itself 🤔 https://github.com/vitejs/vite/issues/15012

I'd appreciate if someone could explain it to me 🙏

**Comment by hi-ogawa** [comment]
@csantos1113 This has been a known workaround on user land (such as the comment suggested in https://github.com/vitejs/vite/issues/15012#issuecomment-1948550039), so this PR only made it applied automatically for react plugin users. It doesn't "fix" the underlying issue, but practically it solved the user-facing issue for Vite users.

**Comment by csantos-nydig** [comment]
@hi-ogawa thanks for the quick response!

Yes, that known workaround is what I had on my codebase as well.

But the thing that intrigued me the most is how a **vitest** plugin solves the warning experience when building w/ vite? Is it being used under the hood somehow?

**Comment by csantos1113** [comment]
@hi-ogawa thanks for the quick response!

Yes, that known workaround is what I had on my codebase as well.

But the thing that intrigued me the most is how a **vitest** plugin solves the warning experience when building w/ **vite**? Is it being used under the hood somehow?

**Comment by hi-ogawa** [comment]
I'm not sure what you mean by "vitest plugin" :thinking: This fix is added to vite react plugin. Also the warning is only coming from "vite build" (which involves rollup) and Vitest doesn't use vite build feature, so I don't think any similar warnings would've appeared for Vitest users.

**Comment by csantos1113** [comment]
🙈 well... that would explain why I was having a hard time understanding the solution: I'm really sorry, I saw "vitejs" on the URLs and was always thinking on "vitest" instead.

All good, and thanks for taking the time for bearing with me on my confusion!

**Comment by jbojcic1** [comment]
I am still seeing this warning on build `Error when using sourcemap for reporting an error: Can't resolve original location of error.`

I am using vite `6.3.5`

**Pull request merged**
