### PR TITLE
fix(ssr-react): remove `context` from `render`

### LINKED ISSUE #227: SSR example misuses React Router v6
### Describe the bug

I was trying to use SSR example. 
https://github.com/vitejs/vite-plugin-react/tree/v4.1.0/playground/ssr-react

What I expect is that the example works correctly.

What actually happening is that the example misuses React Router v6 as if it is v5.
React Router v6 has breaking changes but the commit https://github.com/vitejs/vite-plugin-react/commit/1ea45771bbe62c6e1f06dfe0e2762f9f587ff067 did nothing with that.

For example, it uses `context` prop on `StaticRouter`

https://github.com/vitejs/vite-plugin-react/tree/v4.1.0/playground/ssr-react/src/entry-server.jsx#L7

But `StaticRouter` doesn't have `context` prop.

https://reactrouter.com/en/main/router-components/static-router

### Reproduction

https://github.com/vitejs/vite-plugin-react/tree/v4.1.0/playground/ssr-react

### Steps to reproduce

Run `npm install` followed by `npm run dev`.

### System Info

```shell
% npx envinfo --system --npmPackages '{vite,@vitejs/*}' --binaries --browsers
Need to install the following packages:
  envinfo@7.10.0
Ok to proceed? (y)

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 8.46 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 117.0.5938.88
    Safari: 16.6
  npmPackages:
    @vitejs/plugin-react: ^4.1.0 => 4.1.0
```
```


### Used Package Manager

npm

### Logs

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by chaejunlee**
### Description

closes #227 

The example seems not to be using "Data Router". In that case, we [only provide `location` without `context`](https://reactrouter.com/en/main/guides/ssr#without-a-data-router) to  `<StaticRouter />`. Therefore, I just removed `context` out of the files regarding it.

If it needs an example with "Data Router", I can add one. However, since `react-router` uses `vite`, I don't think the example won't be so much different than the [`react-router` one](https://github.com/remix-run/react-router/tree/dev/examples/ssr-data-router).

So the bottom line is:

1. I have fixed the playground example
2. I think ssr with vite is better explained in `react-router`'s repository

### Additional context

I would like to add some tests around RSC, however because `react-router` only support `loader` pattern of `remix`, not the RSC, it won't be easy.

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md#pull-request-guidelines) and follow the [PR Title Convention](https://github.com/vitejs/vite-plugin-react/blob/main/.github/commit-convention.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by ArnaudBarre** [comment]
Thanks for fixing this. The playground are mostly here for testing purpose and not for example.
With Remix built on top of Vite and the complexity of state of the art SSR with React, I think this is out of the scope of this repo and as you said better handled in other repo that provide better abstractions like Remix

**Comment by thxl2010** [comment]
Excuse me, I'm experiencing an issue with CSS not loading when using [lazy](https://reactrouter.com/en/main/route/lazy) loading.

The manifest contains mappings of module IDs to their associated chunks and asset files.

I did't find `context.modules` for vite react ssr. The [@vitejs/plugin-vue supports it for vue](https://vitejs.dev/guide/ssr.html#generating-preload-directives). What about the @vitejs/plugin-react?

**Comment by hi-ogawa** [comment]
@thxl2010 Can you create a issue to elaborate your setup in detail?

**Comment by thxl2010** [comment]
Here is my question https://github.com/vitejs/vite-plugin-react/discussions/356

react-router/examples/ssr-data-router： https://github.com/remix-run/react-router/blob/4b1f73f3dc5af23a378554ae708105549c8ff82a/examples/ssr-data-router/src/entry.server.tsx#L11

The Vue code I referenced https://github.com/vitejs/vite-plugin-vue/blob/37c9073fb15cf932ee138b0b919c4265cca5fa40/playground/ssr-vue/src/entry-server.js#L22

**Pull request merged**
